swagger: '2.0'
info:
  title: {{cookiecutter.project_name}} API
  description: {{cookiecutter.project_name}} API Description
  version: "0.1"
host: localhost:8000
schemes:
  - http
basePath: /api/v1
produces:
  - application/json